version: '3.7'

services:
  db:
    image: postgres:14
    container_name: st_postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
  
  django:
    build: .
    container_name:  django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: celery -A style_time worker -l INFO
    volumes:
      - .:/usr/src/app
    depends_on:
      - django
      - redis

  redis:
    image: "redis:alpine"

  flower:
    build: .
    command: celery -A style_time flower
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis
    ports:
      - "5555:5555"


      