# Generated by Django 4.2.1 on 2023-06-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='image',
            field=models.ImageField(default='no_image.jpg', upload_to='brand_image/'),
        ),
    ]
