# Generated by Django 4.2.1 on 2023-06-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_manufacture_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacture',
            name='image_brand',
            field=models.ImageField(default='no_image.jpg', upload_to='brand_image/'),
        ),
    ]
