# Generated by Django 4.2.1 on 2023-07-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_manufacture_image_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='features',
            old_name='type',
            new_name='mechanism_type',
        ),
    ]
