# Generated by Django 4.2.1 on 2023-06-26 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Объект заказа', 'verbose_name_plural': 'Объекты заказа'},
        ),
    ]
