# Generated by Django 4.2.1 on 2023-07-20 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_order_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+375\\d{2}\\s\\d{3}-\\d{2}-\\d{2}$')], verbose_name='Телефон'),
        ),
    ]
